#include "stm32f4xx_hal.h"
#include "stm32f4xx.h"
#include "gpio.h"
#include "lis3dsh.h"
#include "global_variables.h"
#include <stdio.h>

// THIS FLAG IS USED BY THE ACCELEROMETER INTERRUPT.
int flagForAccelerometer = 0;

// THIS FLAG IS USED BY THE KEYPAD/7-SEGMENT DISPLAY INTERRUPT.
int flagForKeypad = 0;

// THIS IS THE BUFFER FOR THE INPUT OF THE ACCELEROMETER SENSOR.
float inputBuffer[3];

// THESE VARIABLES STORE THE CURRENT RAW VALUES FROM THE ACCELEROMETER SENSOR.
float accX, accY, accZ;

// THESE CONSTANTS ARE USED TO CALIBRATE THE VALUES OF THE ACCELEROMETER SENSOR.
float	acc11 = 0.00101492331;
float	acc12 = 0.00000698307;
float	acc13 = 0.00000805562;
float	acc10 = 0.00221516886;
float	acc21 = -0.00007170752;
float	acc22 = 0.00095980401;
float	acc23 = 0.00002352682;
float	acc20 = 0.01772957335;
float	acc31 = -0.00010254170;
float	acc32 = -0.00001399401;
float	acc33 = 0.00098730978;
float	acc30 = -0.00523204952;

// THESE VARIABLES STORE THE CURRENT CALIBRATED VALUES.
float normalizedAccX, normalizedAccY, normalizedAccZ;

// THESE ARRAYS KEEP TRACK OF THE LAST THREE UNFILTERED ACCELEROMETER READINGS FOR A PARTICULAR AXIS: {x[n], x[n-1], x[n-2]}.
float unfilteredAccX[3] = {0.0, 0.0, 0.0};
float unfilteredAccY[3] = {0.0, 0.0, 0.0};
float unfilteredAccZ[3] = {0.0, 0.0, 0.0};

// THESE ARRAYS KEEP TRACK OF THE LAST TWO FILTERED ACCELEROMETER VALUES FOR A PARTICULAR AXIS: {y[n-1], y[n-2]}.
float filteredAccX[2] = {0.0, 0.0};
float filteredAccY[2] = {0.0, 0.0};
float filteredAccZ[2] = {0.0, 0.0};

// THESE CONSTANTS ARE THE FILTER COEFFICIENTS.
float b0 = 0.2;
float b1 = 0.2;
float b2 = 0.2;
float a1 = 0.2;
float a2 = 0.2;

// THESE VARIABLES STORE THE CURRENT FILTERED AND CALIBRATED VALUES.
float finalAccX, finalAccY, finalAccZ;

// THESE VARIABLES STORE THE CURRENT ROLL AND PITCH ANGLES.
double rollAngle;
double pitchAngle;

// THESE VARIABLES STORE THE TARGET ROLL AND PITCH ANGLES (ENTERED ON THE KEYPAD).
int targetRollAngle  = 0;
int targetPitchAngle = 0;

// THIS ARRAY KEEPS TRACK OF THE DIGIT TO BE DISPLAYED ON THE 7-SEGMENT DISPLAY.
int digitArray[3] = {0, 0, 0};

// THIS VARIABLE KEEPS TRACK OF WHICH DIGIT OF THE LED DISPLAY SHOULD BE LIGHT UP.
int digitCounter = 0;

// THIS COUNTER IS USED TO REFRESH THE VALUE OF THE 7-SEGMENT DISPLAY EVERY 1 MS.
int refreshCounter = 0;

// THIS VARIABLE KEEPS TRACK OF THE CURRENT KEY PRESSED.
int currentKeyPressed = -1;

// THIS VARIABLE KEEPS TRACK OF HOW LONG A KEY IS PRESSED.
int keyPressedCounter = 0;

// THIS VARIABLE KEEPS TRACK OF THE STATE.
// STATE 1: ENTER ROLL ANGLE.
// STATE 2: ENTER PITCH ANGLE.
// STATE 3: OPERATION MODE.
// STATE 4: SLEEP MODE.
int FSM_state = 1;

// THIS VARIABLE KEEPS TRACK OF WHICH STATE TO GO BACK TO AFTER WAKING UP FROM SLEEP MODE.
int wake_up_state = 1;

// THIS VARIABLE KEEPS TRACK OF WHAT SHOULD BE DISPLAYED IN OPERATION MODE.
// 1: MEASURED ROLL ANGLE.
// 2: MEASURED PITCH ANGLE.
// 3: TARGET ROLL ANGLE.
// 4: TARGET PITCH ANGLE.
int infoDisplayed = 1;
